name: "Tests"
on:
  pull_request:
    branches: main
  push:
    branches: main
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      
      - run: nix-shell --run "nixpkgs-fmt --check ."
      - name: Try latest stable Nix release
        run:  nix-shell -I nixpkgs=nix -p nix --run ./test.sh
      - name: Try tests with nix 2.3
        run:  nix-shell -I nixpkgs=nix -p nix_2_3 --run ./test.sh
